#!/bin/bash
readonly TODO_PATH="/usr/local/share/todo/"
readonly text_editor=nvim
current_day=$(date +"%d/%m/%Y")
get_input_day() {
  if [[ "$1" =~ '/' ]]; then
    IFS='/' read -r -a arr1 <<<"$1"
    IFS='/' read -r -a arr2 <<<"$current_day"

    # Overlay the strings based on slashes
    result="${1%/}"
    for ((i = ${#arr1[@]}; i < ${#arr2[@]}; i++)); do
      result+="/${arr2[i]}"
    done
    if [[  ]]
    formatted=$(echo "$result" | awk -F'/' '{printf("%s/%s/%s\n", $2, $1, $3)}')
    date -d "$formatted" +"%d-%m-%Y"
  else
    date -d "$1 days" +"%d-%m-%Y"
  fi
}
print_todo() {
  echo "TODO LIST:"
  counter=1
  path=$(echo "$TODO_PATH$(echo "$current_day" | tr '/' '-')")
  cat "$path" | while read line; do
    echo "("$counter")" $line
    counter=$((counter + 1))
  done
}
# Check if an argument is provided
if [ -z "$1" ]; then
  print_todo
  exit 1
fi
edit() {
  input=$(get_input_day "$1")
  if [ -z "$input" ]; then
    echo "could not read date"
    exit
  fi
  path=$(echo "$TODO_PATH$(echo "$input" | tr '/' '-')")
  $text_editor "$path"
  if [[ ! -s "$path" ]]; then
    rm "$path"
  fi

}
# Check if the argument equals the match strings
case "$1" in
"h")
  echo "usage: todo [arg]"
  echo "h: print this help"
  echo "num: edit "
  echo "c: clear old dates"
  echo "dd/mm/yyyy: edit date's todo list, can use dd/ or dd/mm as well"
  ;;
"c")
  echo "currently being developed"
  ;;
*)
  edit $1
  ;;
esac
